const roles = [
  "1976 NBA scoring champ Bob McAdoo",
  "Hammy from Over the Hedge",
  "a detective two weeks from retirement",
  "Geoffrey the Giraffe from Toys R Us",
  "an uncharged Roomba",
  "a PSA 9 1st edition Charizard",
  "a rusted-out 2000 Ford Crown Victoria",
  "an overproofed sourdough loaf",
  "my dad still out buying milk and cigarettes",
  "a pee wee hockey coach",
  "a lukewarm cup of coffee",
  "a replacement referee from the 2012 NFL lockout",
  "Alexandra Timoshenko, bronze medalist in rhythmic gymnastics at the 1988 Seoul Olympics",
  "Rick Bosetti, starting center fielder for the 1979 Toronto Blue Jays",
  "the innocent fan Ron Artest grabbed during the 2004 Malice at the Palace",
  "Wayne Gretzky in his one forgettable season as a St. Louis Blue",
  "Arizona Cardinals legend Emmitt Smith",
  "the printed dissenting opinion from Nix v. Hedden, in which the Supreme Court ruled a tomato is legally a vegetable",
  "Sophia Lamb in the eventual BioShock adaptation that we all know is going to disappoint everyone",
  "Chell, who is now inexplicably both a speaking and singing role in a stage musical production of Portal 2",
  "Nana in the hard-R Super Smash Bros film, with Popo being played by Jeremy Strong who has been fully method since the casting announcement",
  "the Panera Bread Psychopath, who abducted three women from the waiting areas of various Panera Bread locations near Lake Michigan and is being written as inexplicably and unnecessarily sexy in an upcoming Netflix limited series",
  "a guy who turned his divorce six years ago into a 47 paragraph post about gratitude, physical fitness, and how it's never been a better time to invest in his new cryptocurrency shitcoin",
  "a person who has responded to every post they have ever seen with either \"great insights\" or \"wow inspirational\" and has never posted original content",
  "the Chief Happiness Officer at yet another AI startup who ends every post with \"thoughts?\" and has never responded to a single comment",
  "Michelangelo's brother, who built all the scaffolding and paid for all the paints and has never once been thanked for it",
  "Phil da Vinci, who is solely responsible for the thing the Mona Lisa does with her eyes and who you have never heard of",
  "the mistress whose existence Charles Darwin had to conceal by inventing the theory of evolution on the spot when his wife caught him",
  "Albert Einstein's cousin, who was in town for the holidays and mockingly wrote e=mc2 on his chalkboard because she thought his work was a waste of time",
  "a direct report of George Washington who would not stop explaining that \"redcoats\" is technically a misnomer because the shade the British wore was not actually red, forcing Washington to cross the Delaware just to get away from him",
  "a participation trophy from a youth soccer league",
  "the guy at a party who will not stop talking about how he almost went pro",
  "a hotel Bible that has seen things",
  "the crucified Jesus at the front of a bombed out church where the main character's unit has decided to wait out a thunderstorm in a World War II movie",
  "the uncle you wish wouldn't come to Thanksgiving",
  "a dance mom",
  "the two pages that are stuck together in an adult magazine",
  "the unfunny straight man on a conspiracy podcast who is always unprepared for recording",
  "a 4:30 AM whiskey coke at the airport bar",
  "the Monster House in a live action remake of the 2006 cult classic Monster House",
  "an English tourist who doesn't understand why she can't find good General Tso's chicken in Vietnam",
  "an ancient copy of Sports Illustrated for Kids at the dentist's office",
  "Inde Navarette's stunt double for Obsession",
  "a cameraman on a Quentin Tarantino movie who is uncomfortable with the number of reshoots he has to do of a shot focusing on the female lead's bare feet",
  "one of the moderators from back when Nathan MacKinnon used to stream Fortnite",
  "a background dancer who the camera focuses on during the Super Bowl halftime show",
  "an extremely toxic Springtrap in the endgame chat after he got zero kills",
  "the person you would've asked to junior prom if you weren't such a little chickenshit",
  "a department store Santa who has been doing this for thirty years and feels nothing",
  "the designer who suggested putting nipples on the batsuit George Clooney wore in Batman and Robin",
];

export default function handler(req, res) {
  const role = roles[Math.floor(Math.random() * roles.length)];
  res.setHeader("Content-Type", "text/plain");
  res.status(200).send(role);
}
